### ISSUE TITLE
Unable yo install python module

### ISSUE THREAD

**Issue by moni2021** [Hax4us/TermuxBlack#32]
I am not able to use trap installed using the script and when i tried to do manual same I got the same error as  :

ERROR: Could not find a version that satisfies the requirement bidict>=0.21.0 (from python-socketio->-r requirements.txt (line 11)) (from versions: 0.1.5, 0.2.1, 0.3.0, 0.3.1, 0.9.0rc0, 0.9.0.post1, 0.10.0, 0.10.0.post1, 0.11.0, 0.12.0.post1, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.15.0.dev0, 0.15.0.dev1, 0.15.0rc1, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4)
ERROR: No matching distribution found for bidict>=0.21.0 (from python-socketio->-r requirements.txt (line 11))

Kindly provide solution

**Comment by Hax4us** [comment]
fixed now so do `apt update && apt install trape`
