### ISSUE TITLE
pkg request = metasploit

### ISSUE THREAD

**Issue by TakshakRamteke** [Hax4us/TermuxBlack#4]

**Comment by Advaithvp** [comment]
You can get metasploit by typing.
``
pkg install git curl wget nmap -y 
and then type..
 curl -LO raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh
 chmod 777 metasploit.sh
 ./metasploit.sh
``
Make sure you have ruby 2.7.2
