### ISSUE TITLE
What is the problem i have did everything perfectly as you mentioned in your trape video by why my ngrok link is not working? And trape control panel is also not updating to slow the users.

### ISSUE THREAD

**Issue by Premjit-Chowdhury** [Hax4us/TermuxBlack#42]
![Screenshot_20210213-200214](https://user-images.githubusercontent.com/72644801/107852429-ab876a80-6e36-11eb-941c-1b86aaabd42c.png)

Please help.. @Hax4us

**Comment by jomon477** [comment]
Bro ngrok works but i will bug .try alternative way bro
