### ISSUE TITLE
Termux Black ==>  have so many bug's

### ISSUE THREAD

**Issue by lusifer123** [Hax4us/TermuxBlack#5]
Please fix this issue... I don't know what the problem.... But file's are not saving or when we use nano or vim text editor.... Text are not delete when press backspace it's move cursor not deleting text.. or ( esc not working.  I don't know my device problem or what).. so please tell me

**Comment by Hax4us** [comment]
I don't think it's because of Termux Black.
Because installing TermuX BlacK includes :
1. Adding new source list 
2. Custom font & color theme 

But you can try to remove font & theme if this is issue ( rm ~/. termux/font.ttf && rm ~/. termux/colors.properties )
