### ISSUE TITLE
I got error code 

### ISSUE THREAD

**Issue by linux-ku** [Hax4us/TermuxBlack#52]
I was want to install the termux black but i got code error when i run command  'sh install.sh' : 
![20210307_111620](https://user-images.githubusercontent.com/56916973/110228804-9fbf2d80-7f36-11eb-8657-04938dbec134.jpg)
"install.sh: 4: [[: not found                         
install.sh: 4: ==: not found                         
install.sh: 50: [[: not found
install.sh: 50: ==: not found"

i was try to use 'bash install.sh' but its doesn't show any and not worked. i tried to reinstall termux but its still not working.

Please help.

**Comment by Hax4us** [comment]
do `bash install.sh` not `sh install.sh`
