### ISSUE TITLE
bad keys 

### ISSUE THREAD

**Issue by p4tetoh** [Hax4us/TermuxBlack#54]
The following signatures were invalid: EXPKEYSIG 5A13A121F25D06F7 lokesh pandey <lkpandey950@gmail.com>
Reading package lists... Done
W: GPG error: https://hax4us.github.io/termux-x pentesting InRelease: The following signatures were invalid: EXPKEYSIG 5A13A121F25D06F7 lokesh pandey <lkpandey950@gmail.com>
E: The repository 'https://hax4us.github.io/termux-x pentesting InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by Hax4us** [comment]
Use `TermuxBlack` repo not `termux-x`
