### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HACKE-RC** [Hax4us/TermuxBlack#7]
E: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock - open (11: Try again)
E: Unable to lock the administration directory (/data/data/com.termux/files/usr/var/lib/dpkg/), is another process using it?

**Comment by TuserAhammed** [comment]
Same problem with me when i try to install lemon,, then 95% and get this error,, fix it sir

**Comment by mangalbimla** [comment]
Same error I am facing

**Comment by HACKE-RC** [comment]
it's due to another process is using apt. first let a apt process complete then make anyother

**Comment by ghost** [comment]
There is another `apt` process that got the *lock* (mutex) which means you are not allowed to run multiple `apt` processes. You could also interrupt it with a signal (For example, `Ctrl` + `C`), if you are definitely sure that there are not any `apt` processes. You can remove `/data/data/com.termux/files/usr/var/lib/dpkg/lock`.

**Comment by 1256-hub-png** [comment]
![Screenshot_2021-10-19-01-06-32-17_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/71225055/137811029-3ddc6f86-d63d-45e6-af26-9b7d7f6c92ff.jpg)
  How to solve it please say 🥺

**Comment by TrackyMayank** [comment]
Just type thus :- dpkg --configure -a

**Comment by Sineyez** [comment]
Lemon tool is not present in termuxblack after installation. I checked in cd .. usr/share and in the list lemon is not available so how do I fix it?

**Comment by Sineyez** [comment]
![Screenshot_20220120-010139_Termux](https://user-images.githubusercontent.com/92973031/150157409-afa7430f-eaa6-4487-aede-58d0c1e26865.jpg)
