### ISSUE TITLE
PGP error

### ISSUE THREAD

**Issue by ghost** [Hax4us/TermuxBlack#76]
GPG error: https://hax4us.github.io/TermuxBlack termuxblack InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4BEE22F&(#;77:)6$!!)_
E: The repository 'https://hax4us.github.io/TermuxBlack termuxblack InRelease' is not signed.
[i] TermuxBlack Installed Successfully.
[i] Now Open New Session & Enjoy (:

**Comment by ChillVibesMushroom** [comment]
> GPG error: https://hax4us.github.io/TermuxBlack termuxblack InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4BEE22F&(#;77:)6$!!)_ E: The repository 'https://hax4us.github.io/TermuxBlack termuxblack InRelease' is not signed. [i] TermuxBlack Installed Successfully. [i] Now Open New Session & Enjoy (:

Did you fix it or not this is bull
