### ISSUE TITLE
apkmod and apmod2 what the difference?

### ISSUE THREAD

**Issue by cadanganrendy** [Hax4us/TermuxBlack#9]
apkmod and apmod2 what the difference?

and can i install both without damaging each other

**Comment by Hax4us** [comment]
Apkmod can :
1. Decompile 
2. Recompile
3. Sign 
4. Zipalign
5. Decode smali to java
6. Enable permissions automatically ( with some exceptions )
7. Bind the metasploit Payload into any app.

I created apkmod2 to bind L3MON RAT into original legit apps.

Apkmod2 is depends on apkmod. 
You can have both at same no issue

**Comment by H420Prajyot** [comment]
@Hax4us 
Apkmod2 error
WARNING: linker: apkmod2: unused DT entry: type 0x1d arg 0x23f
CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced by "apkmod2"...
page record for 0xb6fab02c was not found (block_size=16)
