### ISSUE TITLE
Error downloading updates

### ISSUE THREAD

**Issue by moayad-star** [Hax4us/TermuxBlack#91]
I have a problem while downloading updates in mirrors as well, I need to solve or go back to the basic packages
![Screenshot_20220727_120642_com termux](https://user-images.githubusercontent.com/60769512/181209257-a9e210e2-08f9-49c0-b53d-f63b29367431.jpg)
![Screenshot_20220727_102833_com termux~2](https://user-images.githubusercontent.com/60769512/181209489-4bd7e1a9-d31f-49bc-860d-8887242b0d87.jpg)

**Comment by Sirius-RJ** [comment]
Same

**Comment by MamadM4** [comment]
🪓🥲
